### PR TITLE
add link to allow images to be viewed full-size

### PR DESCRIPTION
**Pull request by elstoc**

### CODE REVIEW

**Comment by elstoc** [comment]
@paperdigits does this look ok to you? Seems to work anyway

**Comment by paperdigits** [comment]
Yes, but I'd add target="_blank" to the link so images open in a new tab.

**Comment by elstoc** [comment]
I can do that if you like but personally I'm not a fan of that behaviour. The problem with that is you give the user no option but to open in a new tab. I prefer to open in the current tab by default with the option to choose new tab if I want.

**Comment by paperdigits** [comment]
I just don't like losing my place because you have to navigate backward. But its not that big of a deal.

**Comment by elstoc** [comment]
Ok I'll merge this for now then. We can change later if needed.

**Pull request merged**
