### PR TITLE
Improve site search

### LINKED ISSUE #297: provide context for search results
When searching the online manual, all that appears is a list of page titles. If the word you're searching for is part of a page title then that works fine, but if the word appears in the page content it's virtually impossible to know which entry to click on unless you know exactly where to find things in the UI. As an example, if you want to know how to remove an image from darktable and you type "remove" into the search box, the actual entry you need (selected images) appears over half way through the results.

This could be made a little less hit-and-miss by taking the user to a results page and highlighting the search term in context.

I have no idea how to do this.

### PR DESCRIPTION
**Pull request by alenaksu**
Hi!

this PR should improves the search results. 
It also changes the UI, adding the page content in the results and highlighting the matched terms.

search-results

fixes darktable-org/dtdocs#297

### CODE REVIEW

**Comment by elstoc** [comment]
This looks awesome thanks @alenaksu. I've done a quick test and it looks like a massive improvement.

**Comment by elstoc** [comment]
I'm good with merging this now if you're finished. I think this probably also resolves https://github.com/darktable-org/dtdocs/issues/72 if I'm not mistaken.

**Comment by alenaksu** [comment]
> I'm good with merging this now if you're finished. I think this probably also resolves [darktable-org/dtdocs#72](https://github.com/darktable-org/dtdocs/issues/72) if I'm not mistaken.

Let me check

**Comment by elstoc** [comment]
Actually one minor issue: if I scroll down the result list the bottom of the page I'm currently viewing disappears. Could the results scroll independently?

Screenshot_2021-07-12_16-43-47

**Comment by elstoc** [comment]
Nice. Should I merge now?

**Comment by alenaksu** [comment]
> Actually one minor issue: if I scroll down the result list the bottom of the page I'm currently viewing disappears. Could the results scroll independently?
> 
> Screenshot_2021-07-12_16-43-47

Pushed a fix for this c653da528afffb60609a5d0e87dca7c00a70df00

Perhaps the UX can be improved further in future PRs.

**Comment by alenaksu** [comment]
> Nice. Should I merge now?

Sure!

**Comment by elstoc** [comment]
Ok this is already a massive improvement. Your contribution is very much appreciated. Merging now!

**Pull request merged**
